### ISSUE TITLE
Start to get a message for the wrong type for LinearGradientProps

### ISSUE THREAD

**Issue by giacomoalonzi** [react-native-svg/react-native-svg#1745]
# Question

Hello there, starting from today after updating these packages:

![image](https://user-images.githubusercontent.com/16420302/162715708-6e74bfcd-9875-4268-8854-f51af7522d2d.png)

I've started to get this message
```
Type '{ children: Element[]; id: string; x1: string; y1: string; x2: string; y2: string; }' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<Component<LinearGradientProps, any, any>> & Readonly<...>'.
  Property 'children' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<Component<LinearGradientProps, any, any>> & Readonly<...>'.ts(2322)
  ```

for every code block, even if I use the example code provided by docs.
what happens?

**Comment by coprocoder** [comment]
I don't understand how the developers could let this happen. The class simply lacked a "children" property. I added it and now it works. This is bad practice, but I haven't found another solution yet. I hope the developer will answer and fix the bug.
![image](https://user-images.githubusercontent.com/71312494/163321496-4e3858f9-782a-4f78-b22b-e31ba0374f80.png)

**Comment by mrsimply** [comment]
It seems to be a general problem coming from @types/react. I also experience this with other libraries. @coprocoder your workaround should not be necessary as the LinearGradientProps are wrapped in React.ComponentClass Type. I guess it's the React team who needs to clean up the v18+ types.

**Comment by JstnEdr** [comment]
This appears to be an intentional decision to force explicit definition of the`children` prop: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/56210

Maybe this will help: https://github.com/eps1lon/types-react-codemod

**Comment by giacomoalonzi** [comment]
> 

So to fix this we have to wait for libraries updates? right?

**Comment by davidskaarup** [comment]
This typing issue also occurs for the `<G>` element

**Comment by coprocoder** [comment]
The latest package version 12.3.0 does not contain this patch. If it was added, please tell me what I need to do to get it. Patch in another branch?

**Comment by WoLewicki** [comment]
Since #1806 has been merged, I think those issues are no longer a problem. Feel free to comment here if I am wrong and we can always reopen it then!

**Comment by SamuelAbip** [comment]
> Since #1806 has been merged, I think those issues are no longer a problem. Feel free to comment here if I am wrong and we can always reopen it then!

I'm having the same problem right now. Tried to use a new project as a test but the node_modules files still seems to include src/index.d.ts, so the imports reference the old interfaces, without the children prop. Do you have any estimative about npm release or am I missing some step?
Thanks for the work!

**Comment by WoLewicki** [comment]
@SamuelAbip can you check if it is fixed in new released v12.4.2 version?

**Comment by SamuelAbip** [comment]
@WoLewicki looks like it is fixed! Thanks!
