### ISSUE TITLE
Typescript Bug: Property 'children' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<Component<LinearGradientProps, any, any>> & Readonly<...>'

### ISSUE THREAD

**Issue by TomasSestak** [react-native-svg/react-native-svg#1798]
Generated icon from SVGR and LinearGradient after update to 12.3.0 cant have children.

`		<Svg fill="none" viewBox="0 0 27 27" {...props}>
			<Path
				d="M13.482 27C6.04 27 0 20.924 0 13.482 0 6.04 6.04 0 13.482 0c7.442 0 13.482 6.04 13.482 13.482 0 7.442-6.04 13.518-13.482 13.518zm0-24.483c-6.04 0-10.965 4.925-10.965 10.965s4.925 10.965 10.965 10.965 10.965-4.925 10.965-10.965c.036-6.04-4.89-10.965-10.965-10.965z"
				fill="url(#prefix__paint0_linear)"
			/>
			<Path d="M14.74 11.181h-2.516v9.995h2.516V11.18z" fill="url(#prefix__paint1_linear)" />
			<Path d="M14.74 6.543h-2.516v2.733h2.516V6.543z" fill="url(#prefix__paint2_linear)" />
			<Defs>
				<LinearGradient id="prefix__paint0_linear" x1={23.5} y1={3} x2={2.5} y2={25.5} gradientUnits="userSpaceOnUse">
					<Stop stopColor={darker} />
					<Stop offset={1} stopColor={lighter} />
				</LinearGradient>
				<LinearGradient id="prefix__paint1_linear" x1={26} y1={5} x2={3} y2={23} gradientUnits="userSpaceOnUse">
					<Stop stopColor={darker} />
					<Stop offset={1} stopColor={lighter} />
				</LinearGradient>
				<LinearGradient id="prefix__paint2_linear" x1={24} y1={3} x2={-1.5} y2={18} gradientUnits="userSpaceOnUse">
					<Stop stopColor={darker} />
					<Stop offset={1} stopColor={lighter} />
				</LinearGradient>
			</Defs>
		</Svg>`

**Comment by TomCorvus** [comment]
React 18?

**Comment by TomasSestak** [comment]
> React 18?

17.0.2 and `"@types/react": "^18.0.15"`

**Comment by TomCorvus** [comment]
´"@types/react": "^18.0.15"´ is for React 18. Downgrade to ´^17´ version

**Comment by mycvlnn** [comment]
I have the same issue.

**Comment by TomCorvus** [comment]
types/react 17 or 18?

**Comment by mrjackdavis** [comment]
Got this issue with `react@18.2.0`, `@types/react@18.0.14` and `react-native@0.69.1`

**Comment by mrjackdavis** [comment]
FWIW, I patched the package like so, and it works as expected. But I'm not confident it's correct

```diff
diff --git a/src/index.d.ts b/src/index.d.ts
index 891a99d1a91c7caaa5b52955205d1dc88d7a8134..01f4194abc235bf452bdc0b35f536b59411f3512 100644
--- a/src/index.d.ts
+++ b/src/index.d.ts
@@ -240,17 +240,17 @@ export interface CircleProps extends CommonPathProps {
   opacity?: NumberProp;
   r?: NumberProp;
 }
-export const Circle: React.ComponentClass<CircleProps>;
-export type Circle = React.ComponentClass<CircleProps>;
+export const Circle: React.ComponentClass<React.PropsWithChildren<CircleProps>>;
+export type Circle = React.ComponentClass<React.PropsWithChildren<CircleProps>>;
 
 export interface ClipPathProps {
   id?: string;
 }
-export const ClipPath: React.ComponentClass<ClipPathProps>;
-export type ClipPath = React.ComponentClass<ClipPathProps>;
+export const ClipPath: React.ComponentClass<React.PropsWithChildren<ClipPathProps>>;
+export type ClipPath = React.ComponentClass<React.PropsWithChildren<ClipPathProps>>;
 
-export const Defs: React.ComponentClass<{}>;
-export type Defs = React.ComponentClass<{}>;
+export const Defs: React.ComponentClass<React.PropsWithChildren<{}>>;
+export type Defs = React.ComponentClass<React.PropsWithChildren<{}>>;
 
 export interface EllipseProps extends CommonPathProps {
   cx?: NumberProp;
@@ -259,14 +259,14 @@ export interface EllipseProps extends CommonPathProps {
   rx?: NumberProp;
   ry?: NumberProp;
 }
-export const Ellipse: React.ComponentClass<EllipseProps>;
-export type Ellipse = React.ComponentClass<EllipseProps>;
+export const Ellipse: React.ComponentClass<React.PropsWithChildren<EllipseProps>>;
+export type Ellipse = React.ComponentClass<React.PropsWithChildren<EllipseProps>>;
 
 export interface GProps extends CommonPathProps, FontProps {
   opacity?: NumberProp;
 }
-export const G: React.ComponentClass<GProps>;
-export type G = React.ComponentClass<GProps>;
+export const G: React.ComponentClass<React.PropsWithChildren<GProps>>;
+export type G = React.ComponentClass<React.PropsWithChildren<GProps>>;
 
 export interface ForeignObjectProps {
   x?: NumberProp;
@@ -274,8 +274,8 @@ export interface ForeignObjectProps {
   width?: NumberProp;
   height?: NumberProp;
 }
-export const ForeignObject: React.ComponentClass<ForeignObjectProps>;
-export type ForeignObject = React.ComponentClass<ForeignObjectProps>;
+export const ForeignObject: React.ComponentClass<React.PropsWithChildren<ForeignObjectProps>>;
+export type ForeignObject = React.ComponentClass<React.PropsWithChildren<ForeignObjectProps>>;
 
 export interface ImageProps
   extends ResponderProps,
@@ -293,8 +293,8 @@ export interface ImageProps
   clipPath?: string;
   id?: string;
 }
-export const Image: React.ComponentClass<ImageProps>;
-export type Image = React.ComponentClass<ImageProps>;
+export const Image: React.ComponentClass<React.PropsWithChildren<ImageProps>>;
+export type Image = React.ComponentClass<React.PropsWithChildren<ImageProps>>;
 
 export interface LineProps extends CommonPathProps {
   opacity?: NumberProp;
@@ -303,8 +303,8 @@ export interface LineProps extends CommonPathProps {
   y1?: NumberProp;
   y2?: NumberProp;
 }
-export const Line: React.ComponentClass<LineProps>;
-export type Line = React.ComponentClass<LineProps>;
+export const Line: React.ComponentClass<React.PropsWithChildren<LineProps>>;
+export type Line = React.ComponentClass<React.PropsWithChildren<LineProps>>;
 
 export interface LinearGradientProps {
   x1?: NumberProp;
@@ -315,15 +315,15 @@ export interface LinearGradientProps {
   gradientTransform?: ColumnMajorTransformMatrix | string;
   id?: string;
 }
-export const LinearGradient: React.ComponentClass<LinearGradientProps>;
-export type LinearGradient = React.ComponentClass<LinearGradientProps>;
+export const LinearGradient: React.ComponentClass<React.PropsWithChildren<LinearGradientProps>>;
+export type LinearGradient = React.ComponentClass<React.PropsWithChildren<LinearGradientProps>>;
 
 export interface PathProps extends CommonPathProps {
   d?: string;
   opacity?: NumberProp;
 }
-export const Path: React.ComponentClass<PathProps>;
-export type Path = React.ComponentClass<PathProps>;
+export const Path: React.ComponentClass<React.PropsWithChildren<PathProps>>;
+export type Path = React.ComponentClass<React.PropsWithChildren<PathProps>>;
 
 export interface PatternProps {
   id?: string;
@@ -337,22 +337,22 @@ export interface PatternProps {
   viewBox?: string;
   preserveAspectRatio?: string;
 }
-export const Pattern: React.ComponentClass<PatternProps>;
-export type Pattern = React.ComponentClass<PatternProps>;
+export const Pattern: React.ComponentClass<React.PropsWithChildren<PatternProps>>;
+export type Pattern = React.ComponentClass<React.PropsWithChildren<PatternProps>>;
 
 export interface PolygonProps extends CommonPathProps {
   opacity?: NumberProp;
   points?: string | ReadonlyArray<NumberProp>;
 }
-export const Polygon: React.ComponentClass<PolygonProps>;
-export type Polygon = React.ComponentClass<PolygonProps>;
+export const Polygon: React.ComponentClass<React.PropsWithChildren<PolygonProps>>;
+export type Polygon = React.ComponentClass<React.PropsWithChildren<PolygonProps>>;
 
 export interface PolylineProps extends CommonPathProps {
   opacity?: NumberProp;
   points?: string | ReadonlyArray<NumberProp>;
 }
-export const Polyline: React.ComponentClass<PolylineProps>;
-export type Polyline = React.ComponentClass<PolylineProps>;
+export const Polyline: React.ComponentClass<React.PropsWithChildren<PolylineProps>>;
+export type Polyline = React.ComponentClass<React.PropsWithChildren<PolylineProps>>;
 
 export interface RadialGradientProps {
   fx?: NumberProp;
@@ -366,8 +366,8 @@ export interface RadialGradientProps {
   gradientTransform?: ColumnMajorTransformMatrix | string;
   id?: string;
 }
-export const RadialGradient: React.ComponentClass<RadialGradientProps>;
-export type RadialGradient = React.ComponentClass<RadialGradientProps>;
+export const RadialGradient: React.ComponentClass<React.PropsWithChildren<RadialGradientProps>>;
+export type RadialGradient = React.ComponentClass<React.PropsWithChildren<RadialGradientProps>>;
 
 export interface RectProps extends CommonPathProps {
   x?: NumberProp;
@@ -378,16 +378,16 @@ export interface RectProps extends CommonPathProps {
   ry?: NumberProp;
   opacity?: NumberProp;
 }
-export const Rect: React.ComponentClass<RectProps>;
-export type Rect = React.ComponentClass<RectProps>;
+export const Rect: React.ComponentClass<React.PropsWithChildren<RectProps>>;
+export type Rect = React.ComponentClass<React.PropsWithChildren<RectProps>>;
 
 export interface StopProps {
   stopColor?: Color;
   stopOpacity?: NumberProp;
   offset?: NumberProp;
 }
-export const Stop: React.ComponentClass<StopProps>;
-export type Stop = React.ComponentClass<StopProps>;
+export const Stop: React.ComponentClass<React.PropsWithChildren<StopProps>>;
+export type Stop = React.ComponentClass<React.PropsWithChildren<StopProps>>;
 
 export interface SvgProps extends GProps, ReactNative.ViewProperties {
   width?: NumberProp;
@@ -399,8 +399,8 @@ export interface SvgProps extends GProps, ReactNative.ViewProperties {
 }
 
 // Svg is both regular and default exported
-export const Svg: React.ComponentClass<SvgProps>;
-export type Svg = React.ComponentClass<SvgProps>;
+export const Svg: React.ComponentClass<React.PropsWithChildren<SvgProps>>;
+export type Svg = React.ComponentClass<React.PropsWithChildren<SvgProps>>;
 export default Svg;
 
 export interface SymbolProps {
@@ -409,8 +409,8 @@ export interface SymbolProps {
   preserveAspectRatio?: string;
   opacity?: NumberProp;
 }
-export const Symbol: React.ComponentClass<SymbolProps>;
-export type Symbol = React.ComponentClass<SymbolProps>;
+export const Symbol: React.ComponentClass<React.PropsWithChildren<SymbolProps>>;
+export type Symbol = React.ComponentClass<React.PropsWithChildren<SymbolProps>>;
 
 export interface TSpanProps extends CommonPathProps, FontProps {
   x?: NumberArray;
@@ -420,8 +420,8 @@ export interface TSpanProps extends CommonPathProps, FontProps {
   rotate?: NumberArray;
   inlineSize?: NumberProp;
 }
-export const TSpan: React.ComponentClass<TSpanProps>;
-export type TSpan = React.ComponentClass<TSpanProps>;
+export const TSpan: React.ComponentClass<React.PropsWithChildren<TSpanProps>>;
+export type TSpan = React.ComponentClass<React.PropsWithChildren<TSpanProps>>;
 
 export interface TextSpecificProps extends CommonPathProps, FontProps {
   alignmentBaseline?: AlignmentBaseline;
@@ -442,8 +442,8 @@ export interface TextProps extends TextSpecificProps {
   opacity?: NumberProp;
   inlineSize?: NumberProp;
 }
-export const Text: React.ComponentClass<TextProps>;
-export type Text = React.ComponentClass<TextProps>;
+export const Text: React.ComponentClass<React.PropsWithChildren<TextProps>>;
+export type Text = React.ComponentClass<React.PropsWithChildren<TextProps>>;
 
 export interface TextPathProps extends TextSpecificProps {
   xlinkHref?: string;
@@ -453,8 +453,8 @@ export interface TextPathProps extends TextSpecificProps {
   spacing?: TextPathSpacing;
   midLine?: TextPathMidLine;
 }
-export const TextPath: React.ComponentClass<TextPathProps>;
-export type TextPath = React.ComponentClass<TextPathProps>;
+export const TextPath: React.ComponentClass<React.PropsWithChildren<TextPathProps>>;
+export type TextPath = React.ComponentClass<React.PropsWithChildren<TextPathProps>>;
 
 export interface UseProps extends CommonPathProps {
   xlinkHref?: string;
@@ -465,8 +465,8 @@ export interface UseProps extends CommonPathProps {
   y?: NumberProp;
   opacity?: NumberProp;
 }
-export const Use: React.ComponentClass<UseProps>;
-export type Use = React.ComponentClass<UseProps>;
+export const Use: React.ComponentClass<React.PropsWithChildren<UseProps>>;
+export type Use = React.ComponentClass<React.PropsWithChildren<UseProps>>;
 
 export enum EMaskUnits {
   USER_SPACE_ON_USE = 'userSpaceOnUse',
@@ -487,8 +487,8 @@ export interface MaskProps extends CommonPathProps {
   maskUnits?: TMaskUnits;
   maskContentUnits?: TMaskUnits;
 }
-export const Mask: React.ComponentClass<MaskProps>;
-export type Mask = React.ComponentClass<MaskProps>;
+export const Mask: React.ComponentClass<React.PropsWithChildren<MaskProps>>;
+export type Mask = React.ComponentClass<React.PropsWithChildren<MaskProps>>;
 
 export enum MarkerUnits {
   STROKE_WIDTH = 'strokeWidth',
@@ -511,8 +511,8 @@ export interface MarkerProps {
   markerUnits?: MarkerUnits;
   orient?: Orient | NumberProp;
 }
-export const Marker: React.ComponentClass<MarkerProps>;
-export type Marker = React.ComponentClass<MarkerProps>;
+export const Marker: React.ComponentClass<React.PropsWithChildren<MarkerProps>>;
+export type Marker = React.ComponentClass<React.PropsWithChildren<MarkerProps>>;
 
 export type Styles = { [property: string]: string };
 
@@ -562,15 +562,15 @@ export function parse(source: string, middleware?: Middleware): JsxAST | null;
 export const SvgAst: React.FunctionComponent<AstProps>;
 
 export const SvgXml: React.FunctionComponent<XmlProps>;
-export const SvgFromXml: React.ComponentClass<XmlProps, XmlState>;
+export const SvgFromXml: React.ComponentClass<React.PropsWithChildren<XmlProps>, XmlState>;
 
 export const SvgUri: React.FunctionComponent<UriProps>;
-export const SvgFromUri: React.ComponentClass<UriProps, UriState>;
+export const SvgFromUri: React.ComponentClass<React.PropsWithChildren<UriProps>, UriState>;
 
 export const SvgCss: React.FunctionComponent<XmlProps>;
-export const SvgWithCss: React.ComponentClass<XmlProps, XmlState>;
+export const SvgWithCss: React.ComponentClass<React.PropsWithChildren<XmlProps>, XmlState>;
 
 export const SvgCssUri: React.FunctionComponent<UriProps>;
-export const SvgWithCssUri: React.ComponentClass<UriProps, UriState>;
+export const SvgWithCssUri: React.ComponentClass<React.PropsWithChildren<UriProps>, UriState>;
 
 export const inlineStyles: Middleware;

```

**Comment by TomCorvus** [comment]
See https://github.com/DefinitelyTyped/DefinitelyTyped/pull/56210

**Comment by skam22** [comment]
you can fix this by first installing [patch-package ](https://github.com/ds300/patch-package).

in VSCode, command click `<LinearGradient>` to pull up the definition file located at project/node_modules/react-native-svg/src.

edit LinearGradientProps to add in the missing children prop like this:

```
export interface LinearGradientProps {
  x1?: NumberProp;
  x2?: NumberProp;
  y1?: NumberProp;
  y2?: NumberProp;
  gradientUnits?: Units;
  gradientTransform?: ColumnMajorTransformMatrix | string;
  id?: string;
  children?: React.ReactNode;  // <--- ADD THIS LINE
}
```

then save your patch:

```
yarn patch-package react-native-svg
```

the error will be resolved.  since you'll have to do this frequently (as a number of packages are showing this typescript error after implicit children was removed) I suggest you use patch-package so that your modifications to the node_modules are automatically reapplied after every package install.

**Comment by justinbhopper** [comment]
Looks like #1806 addresses this bug.

**Comment by WoLewicki** [comment]
As @justinbhopper mentioned, since https://github.com/react-native-svg/react-native-svg/pull/1806 has been merged, I think those issues are no longer a problem. Feel free to comment here if I am wrong and we can always reopen it then!

**Comment by AHMED-5G** [comment]
`export interface RadialGradientProps {
  fx?: NumberProp;
  fy?: NumberProp;
  rx?: NumberProp;
  ry?: NumberProp;
  cx?: NumberProp;
  cy?: NumberProp;
  r?: NumberProp;
  gradientUnits?: Units;
  gradientTransform?: ColumnMajorTransformMatrix | string;
  id?: string;
  children?:React.ReactElement | React.ReactElement[]
}`

**Comment by AHMED-5G** [comment]
`ts
export interface RadialGradientProps {
  fx?: NumberProp;
...
  children?:React.ReactElement | React.ReactElement[]  add this 
}

`
